### PR TITLE
Add lockfiles to .gitignore

### PR DESCRIPTION
**Pull request by aleksrutins**
Some package managers (yarn, pnpm, etc.) use their own lockfiles and it can cause problems to have lockfiles from multiple different package managers in the repository.

### CODE REVIEW

**Comment by ItsHarper** [comment]
Nice sticker on your laptop, haha (I work for REV).

The whole point of a lockfile is so to make sure that all developers use the exact same dependency versions. You are absolutely supposed to check them in into source control, and then everybody using the project should use the package manager that is compatible with that lockfile (in this case NPM). Which package manager you use should be a per-project decision. 

I'm not affiliated with the project in any way, just providing my review.

**Comment by aleksrutins** [comment]
From what I understand, you put your versions in `package.json`, and then those dependencies specify the versions of their dependencies. You still have the same amount of versioning info, but taking up less disk space and without package-manager conflicts (for example, Yarn will throw an error if you have a `package-lock.json`).

That's how I understand it.

**Comment by aleksrutins** [comment]
Never mind, just saw [this blog post](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/), and it has enlightened me.

**Comment by ItsHarper** [comment]
Yay learning!

**Pull request closed without merging**
